Movieapp/urls.py
from django.urls import path

from Movieapp import views
app_name='Movieapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:movieid>/', views.details, name='details'),
    path('add_movie/', views.add_movie, name='add_movie'),
    path('update_movie/<int:id>/', views.update_movie, name='update_movie'),
    path('delete_movie/<int:id>/', views.delete, name='delete_movie'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('update_user/<int:id>/', views.update_user, name='update_user'),
    path('user/<int:user_id>/', views.user_details, name='user_details'),
    path('search/', views.Searchresults, name='search'),

]

Movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Movieapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Movieapp/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db import models



class CustomUser(AbstractUser):
    pass

class Movie(models.Model):
    title = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='pics', null=True)
    category = models.CharField(max_length=250)
    languages = models.CharField(max_length=250)
    actors = models.CharField(max_length=250, null=True)
    year = models.DateField()
    link = models.CharField(max_length=250, default=None, null=True)
    rating = models.FloatField(null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

Movieapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import *

class movieform(forms.ModelForm):
    class Meta:
        model=Movie
        fields=('title','description','image','category','languages','actors','year','link','rating')

class CustomUserCreationForm(UserCreationForm):


    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name','email','password1', 'password2')

class MovieUpdateForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(MovieUpdateForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.required = False

class CustomUserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email']  # Include only the fields you need

    def __init__(self, *args, **kwargs):
        super(CustomUserUpdateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.required = False
            field.help_text = ''

Movieapp/views.py
# Create your views here.
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import CustomUser, Movie
from .forms import *
from django.db.models import Q
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger

def index(request):
    allmovies = Movie.objects.select_related('user').all()
    return render(request,'index.html',{'allmovies':allmovies})

def details(request,movieid):
    movie = get_object_or_404(Movie, pk=movieid)
    return render(request,'details.html',{'movie':movie})

@login_required
def add_movie(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        image = request.FILES.get('image')
        category = request.POST.get('category')
        languages = request.POST.get('languages')
        actors = request.POST.get('actors')
        year = request.POST.get('year')
        link = request.POST.get('link')
        rating = request.POST.get('rating')


        if request.user.is_authenticated:
            movie = Movie(
                title=title,
                description=description,
                image=image,
                category=category,
                languages=languages,
                actors=actors,
                year=year,
                link=link,
                rating=rating,
                user=request.user
            )
            movie.save()
            messages.info(request, "Movie successfully added")
            return redirect("Movieapp:user_profile")
        else:
            messages.error(request, "You must be logged in to add a movie")
            return redirect("Movieapp:login")

    return render(request, 'addmovies.html')




@login_required
def update_movie(request, id):
    movie = get_object_or_404(Movie, id=id)
    form = MovieUpdateForm(request.POST or None, request.FILES or None, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('Movieapp:user_profile')
    return render(request, 'update_movie.html', {'form': form, 'movie': movie})
@login_required
def delete(request,id):
    movie = get_object_or_404(Movie, id=id)
    if request.method == 'POST':
        movie.delete()
        return redirect('Movieapp:user_profile')
    return render(request,'delete.html',{"movie":movie})

@login_required
def user_profile(request):
    current_user = request.user
    user_movies = Movie.objects.filter(user=current_user)
    return render(request, 'profile.html', {'allmovies': user_movies, 'user': current_user})

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.info(request,"User created successfully")
            auth.login(request, user)
            return redirect('Movieapp:login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'register.html', {'form': form})



def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            request.session.set_expiry(86400)
            return redirect('Movieapp:user_profile')
        else:
            messages.info(request,"invalid credentails")
            return redirect("Movieapp:login")
    return render(request,"login.html")
@login_required
def logout(request):
    auth.logout(request)
    return redirect("/")
@login_required
def update_user(request, id):
    user = get_object_or_404(CustomUser, id=id)
    form = CustomUserUpdateForm(request.POST or None, request.FILES or None, instance=user)
    if form.is_valid():
        form.save()
        return redirect('Movieapp:user_profile')
    return render(request, 'update_user.html', {'form': form, 'user': user})
@login_required
def user_details(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    movies = Movie.objects.filter(user=user)
    return render(request,'user_details.html', {'user': user, 'movies': movies})







def Searchresults(request):
    query = request.GET.get('q', '')
    movie_list = Movie.objects.all()

    if query:
        movie_list = movie_list.filter(Q(name__icontains=query) | Q(description__icontains=query))

    # Pagination setup
    paginator = Paginator(movie_list, 10)  # Show 10 movies per page
    page_number = request.GET.get('page')

    try:
        movies = paginator.page(page_number)
    except PageNotAnInteger:

        movies = paginator.page(1)
    except EmptyPage:

        movies = paginator.page(paginator.num_pages)

    return render(request, 'search.html', {'query': query, 'movies': movies})

templates/addmovies.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
       {% if messages %}
    <div class="alert alert-info" role="alert">
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Add Movie</h3>
            <!-- Start of form -->
            <form action="{% url 'Movieapp:add_movie' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- Title field -->
                <div class="form-group">
                    <label for="id_title">Title:</label>
                    <input type="text" id="id_title" name="title" class="form-control">
                </div>

                <!-- Description field -->
                <div class="form-group">
                    <label for="id_description">Description:</label>
                    <textarea id="id_description" name="description" class="form-control"></textarea>
                </div>

                <!-- Image field -->
                <div class="form-group">
                    <label for="id_image">Image:</label>
                    <input type="file" id="id_image" name="image" class="form-control-file">
                </div>

                <!-- Category field -->
                <div class="form-group">
                    <label for="id_category">Category:</label>
                    <select id="id_category" name="category" class="form-control">
                        <option value="A">ACTION</option>
                        <option value="D">DRAMA</option>
                        <option value="C">COMEDY</option>
                        <option value="R">ROMANCE</option>
                    </select>
                </div>

                <!-- Languages field -->
                <div class="form-group">
                    <label for="id_languages">Languages:</label>
                    <select id="id_languages" name="languages" class="form-control">
                        <option value="EN">ENGLISH</option>
                        <option value="GR">TAMIL</option>
                        <option value="MAL">MALAYALAM</option>
                        <option value="TEL">TELUGU</option>
                        <option value="HI">HINDI</option>
                        <option value="KA">KANNADA</option>
                        <option value="OR">OTHERS</option>
                    </select>
                </div>

                <!-- Actors field -->
                <div class="form-group">
                    <label for="id_actors">Actors:</label>
                    <input type="text" id="id_actors" name="actors" class="form-control">
                </div>

                <!-- Year field -->
                <div class="form-group">
                    <label for="id_year">Year:</label>
                    <input type="date" id="id_year" name="year" class="form-control">
                </div>

                <!-- Link field -->
                <div class="form-group">
                    <label for="id_link">Link:</label>
                    <input type="text" id="id_link" name="link" class="form-control">
                </div>

                <!-- Rating field -->
                <div class="form-group">
                    <label for="id_rating">Rating:</label>
                    <input type="number" id="id_rating" name="rating" class="form-control">
                </div>

                <!-- Submit button -->
                <div class="text-center">
                    <input type="submit" class="btn btn-primary mt-3" value="Add Movie">
                </div>

            </form>
            <!-- End of form -->
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Movie Updates</title>

  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white" id="bg-nav">
  <a class="navbar-brand" href="{% url 'Movieapp:index'%}">Movie Updates</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Movieapp:login' %}">Log In<span class="sr-only">(current)</span></a>
      </li>





    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'Movieapp:search' %}" method="get">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <h1 class="text-center">Movie Updates</h1>
    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/base1.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Movie Updates</title>

  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white" id="bg-nav">
  <a class="navbar-brand" href="/">Movie Updates</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>

      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'Movieapp:update_movie'%}">Add Movie <span class="sr-only">(current)</span></a>

      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'Movieapp:user_profile'%}">Profile <span class="sr-only">(current)</span></a>

      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Movieapp:logout' %}">Log Out<span class="sr-only">(current)</span></a>
      </li>





    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <h1 class="text-center">Movie Updates</h1>
    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/details.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <center>
                                <img src="{{ movie.image.url }}" style="width:150px;height:150px;" align="left">
                            </center>
                            <h2 class="text-center">{{ movie.title }}</h2>
                            <div class="text-center"><i>{{ movie.year }}</i></div>
                            <p class="text-center">{{ movie.description }}</p>
                            <h5 class="text-center">{{ movie.category }}</h5>
                            <h5 class="text-center">{{ movie.actors }}</h5>
                            <h5 class="text-center">{{ movie.languages }}</h5>
                            <h5 class="text-center"><a href="{{ movie.link }}" target="_blank">Trailer:{{ movie.link }}</a></h5>
                            <p>Uploaded by: {{ movie.user.username }}</p>

                            <!-- Link Button to Update Movie Details -->
                            <div class="text-center mt-3">
                                <a href="{% url 'Movieapp:update_movie' movie.id %}" class="btn btn-primary">Update Movie Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h2 class="text-center">All Movie Updates</h2>


<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row">
                {% for movies in allmovies %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <center> <a href="{% url 'Movieapp:details' movies.id %}" ><img src="{{ movies.image.url }}" style="width:150px;height:150px;"></a> </center>
                            <h5 class="text-center">{{ movies.title }}</h5>
                            <div class="text-center"><i>{{ movies.year }}</i></div>
                            <div class="text-center"><i>Rating {{ movies.rating }}</i></div>

                            <div class="text-center"><i>Uploaded by {{ movies.user.username }}</i></div>

                        </div>
                    </div>

                </div>
                {% endfor %}
            </div>
        </div>

    </div>
</div>


{% endblock%}

templates/login.html
cd {% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
     {% if messages %}
    <div class="alert alert-info" role="alert">
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}
    <div class="card mx-auto" style="width: 50%;">
        <div class="card-body">
            <h3 class="text-center">Sign In</h3>
            <!-- Start of form -->
            <form action="{% url 'Movieapp:login' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label>Username</label>
                    <input type="text" id="username" name="username" class="form-control">
                </div>

                <div class="form-group">
                    <label>Password</label>
                    <input type="password" id="password" name="password" class="form-control">
                </div>

                <div class="text-center">
                    <input type="submit" class="btn btn-primary mt-3" value="Sign In">
                </div>

                <div class="text-center">
                    <i> Don't have an account? <a href="{% url 'Movieapp:register' %}">Sign Up</a></i>
                </div>

            </form>
            <!-- End of form -->
        </div>
    </div>
</div>
{% endblock %}

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Website{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- Custom CSS -->
    <style>

        .profile-image {
            max-width: 150px;
            height: auto;
            border-radius: 50%;
        }
    </style>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'Movieapp:index' %}">Movie Updates</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">


                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Movieapp:user_details' user.id %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Movieapp:add_movie' %}">Add Movie</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Movieapp:logout' %}">Logout</a>
                </li>

                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Main content -->
    <div class="container mt-4">
        <h4 align="center">Your Updates</h4>
        {% block content %}
        <div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row">
                {% for movies in allmovies %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <center> <a href="{% url 'Movieapp:details' movies.id  %}" ><img src="{{ movies.image.url }}" style="width:150px;height:150px;"></a> </center>
                            <h5 class="text-center">{{ movies.title }}</h5>
                            <div class="text-center"><i>{{ movies.year }}</i></div>

                        </div>
                    </div>

                </div>
                {% endfor %}
            </div>
        </div>

    </div>
</div>

        {% endblock %}
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-4G0+wrDSu2t6G9bTZDHNYOTk+P5QZ3J1/Cjz0e8eoU3ncs+l1OwDffs67B1z0P4P" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh/jFcZ5TG8g2HRjuB/XE3I7k9kRUy2I6LGzB" crossorigin="anonymous"></script>
</body>
</html>

templates/user_details.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>User Details</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Movie Updates</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Movieapp:add_movie' %}">Add Movie</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Movieapp:logout' %}">Log Out</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card">
                    <div class="card-header">
                        <h1>{{ user.username }}'s Profile</h1>
                    </div>
                    <div class="card-body">
                        <p><strong>Email:</strong> {{ user.email }}</p>
                        <p><strong>First Name:</strong> {{ user.first_name }}</p>
                        <p><strong>Last Name:</strong> {{ user.last_name }}</p>
                         <a href="{% url 'Movieapp:update_user' user.id %}" class="btn btn-primary">Update User Details</a>
                    </div>
                </div>

                <div class="card mt-4">
                    <div class="card-header">
                        <h2>Movies Added by {{ user.username }}</h2>
                    </div>
                    <div class="card-body">
                        <ul class="list-group">
                            {% for movie in movies %}
                                <li class="list-group-item">{{ movie.title }} ({{ movie.year }})</li>
                            <li class="list-group-item"><img src="{{ movie.image.url }}" style="width:150px;height:150px;"></li>
                            <li class="list-group-item">{{ movie.description }}</li>
                            <li class="list-group-item">{{ movie.category }} </li>
                            <li class="list-group-item">{{ movie.rating}}</li>
                            <li class="list-group-item"><a href="{{ movie.link.url }}">{{movie.link}}</a></li>
                            <a href="{% url 'Movieapp:update_movie' movie.id %}" class="btn btn-primary">Update Movie Details</a>
                            <a href="{% url 'Movieapp:delete_movie' movie.id %}" class="btn btn-danger">Delete Movie Details</a>

                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>